window.options = [
    {
        title: "Study details",
        params: {
            Operator: {
                title: "Performed by:",
                custom: true, 
            },
            TechnicalQualilty: {
                title: "Technical quality:",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Good", title: "Good" },
                    { label: "Fair", title: "Fair", default: true },
                    { label: "Poor", title: "Poor -" },
                    { label: "Very poor", title: "Very poor -" },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
            },
            Machine: {
                title: "Machine:",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "GE Pioneer", title: "GE Pioneer" },
                    { label: "GE 95", title: "GE E95", default: true },
                    { label: "GE S70", title: "GE S70" },
                    { label: "GE iQ", title: "GE iQ" },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
            },
            Rhythm: {
                title: "Rhythm",
                custom: true, 
                conditionalText: true,
                options: [
                    { label: "Sinus rhythm", title: "Sinus rhythm", default: true },
                    { label: "AF", title: "Atrial fibrillation" },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
            },
            Gender: {
                title: "Gender",
                conditionalText: true,
                options: [
                    { label: "Male", title: "Male", default: true },
                    { label: "Female", title: "Female" },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
            },
        },
    },
    {
        title: "Left Ventricle",
        params: {
            RWMAs: {
                title: "RWMAs",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "(No RWMAs)", title: "", default: true },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                large: true,
                enableSummary: true,
                summaryDefault: true,
                summaryOnChange: true,
                summaryOrder: 0,
            },
            LVSF: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Normal systolic function", title: "Normal left ventricular systolic function", default: true },
                    { label: "Borderline low systolic function", title: "Borderline low left ventricular systolic function" },
                    { label: "Impaired systolic function", title: "Impaired left ventricular systolic function" },
                    { label: "Severely impaired systolic function", title: "Severely impaired left ventricular systolic function" },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOrder: 1,
            },
            LVH: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Normal wall thickness", title: "Normal wall thickness", default: true },
                    { label: "Concentric hypertrophy", title: "Concentric hypertrophy" },
                    { label: "Concentric remodelling", title: "Concentric remodelling" },
                    { label: "Eccentric hypertrophy", title: "Eccentric hypertrophy" },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOrder: 2,
            },
            LVD: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Normal dimensions", title: "Normal left ventricular internal dimensions", default: true },
                    { label: "Mild dilatation", title: "Mild left ventricular dilatation" },
                    { label: "Moderate dilatation", title: "Moderate left ventricular dilatation" },
                    { label: "Severe dilatation", title: "Severe left ventricular dilatation" },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOrder: 3,
            },
            Diastology: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Normal diastolic function", title: "Normal diastolic function", default: true },
                    { label: "Impaired diastolic function", title: "Impaired diastolic function" },
                    { label: "Indeterminate diastolic function", title: "Indeterminate diastolic function" },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOrder: 4,
            },
            LAP: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "(filling pressure)", title: ".", default: true },
                    { label: "Normal filling pressure", title: ", normal filling pressure." },
                    { label: "Indeterminate filling pressure", title: ", indeterminate filling pressure." },
                    { label: "Elevated filling pressure", title: ", elevated filling pressure." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOrder: 5,
            },
        },
    },
    {
        title: "Mitral Valve",
        params: {
            MV: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Normal leaflets", title: "Leaflets are thin and mobile. Valve opens well.", default: true },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
            },
            MS: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No stenosis", title: "No mitral stenosis.", default: true },
                    { label: "Mild stenosis", title: "Mild mitral stenosis." },
                    { label: "Moderate stenosis", title: "Moderate mitral stenosis." },
                    { label: "Severe stenosis", title: "Severe mitral stenosis." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOnChange: true,
                summaryOrder: 31,
            },
            MR: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Trivial regurgitation", title: "Trivial mitral regurgitation.", default: true },
                    { label: "Mild regurgitation", title: "Mild mitral regurgitation." },
                    { label: "Moderate regurgitation", title: "Moderate mitral regurgitation." },
                    { label: "Severe regurgitation", title: "Severe mitral regurgitation." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOnChange: true,
                summaryOrder: 32,
            },
        },
    },
    {
        title: "Left Atirum",
        params: {
            LAtrium: {
                title: "",
                custom: true, 
                conditionalText: true,
                options: [
                    { label: "Normal size", title: "Normal size.", default: true },
                    { label: "Borderline dilated", title: "Borderline dilated." },
                    { label: "Dilated", title: "Dilated." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
            },
        },
    },
    {
        title: "Aortic Valve",
        params: {
            AV: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Trileaflet, normal", title: "Trileaflet, cusps appear thin and mobile, opens well.", default: true },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
            },
            AS: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No stenosis", title: "No aortic stenosis.", default: true },
                    { label: "Mild stenosis", title: "Mild aortic stenosis." },
                    { label: "Moderate stenosis", title: "Moderate aortic stenosis." },
                    { label: "Severe stenosis", title: "Severe aortic stenosis." },
                    { label: "Very severe stenosis", title: "very severe aortic stenosis." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOnChange: true,
                summaryOrder: 33,
            },
            AR: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No regurgitation", title: "No aortic regurgitation.", default: true },
                    { label: "Trivial regurgitation", title: "Trivial aortic regurgitation." },
                    { label: "Mild regurgitation", title: "Mild aortic regurgitation." },
                    { label: "Moderate regurgitation", title: "Moderate aortic regurgitation." },
                    { label: "Severe regurgitation", title: "Severe aortic regurgitation." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOnChange: true,
                summaryOrder: 34,
            },
            AVGradient: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No AV gradient", title: "No AV gradient demonstrated.", default: true },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
            },
            LVOTGradient: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No LVOT gradient", title: "No LVOT gradient demonstrated.", default: true },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
            },
        },
    },
    {
        title: "Aorta",
        params: {
            Aorta: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Normal size", title: "Normal size.", default: true },
                    { label: "Dilated root and ascending", title: "Dilated aortic root and proximal ascending aorta." },
                    { label: "Dilated root only", title: "Dilated aortic root.\nThe proximal ascending aorta is not dilated." },
                    { label: "Dilated ascending aorta only", title: "Dilated proximal ascending aorta.\nThe aortic root is not dilated." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOnChange: true,
                summaryOrder: 40,
            },
            Arch: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Normal arch Doppler", title: "Aortic Arch Doppler studies normal.", default: true },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOnChange: true,
                summaryOrder: 41,
            },
            AoReversal: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No reversal", title: "No flow reversal seen in the arch.", default: true },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOnChange: true,
                summaryOrder: 42,
            },
            Coarc: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No coarctation", title: "No coarctation of the descending aorta.", default: true },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOnChange: true,
                summaryOrder: 43,
            },
        },
    },
    {
        title: "Right Ventricle",
        params: {
            RVD: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Normal size", title: "Normal right ventricular size.", default: true },
                    { label: "Dilated", title: "Dilated right ventricle." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOrder: 11,
            },
            RVH: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No hypertrophy", title: "Visually, no right ventricular hypertrophy.", default: true },
                    { label: "Hypertrophied", title: "Right ventricular hypertrophy." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOrder: 12,
            },
            RVFr: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Normal radial function", title: "Normal radial function.", default: true },
                    { label: "Impaired radial function", title: "Impaired radial function." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOrder: 13,
            },    
            RVFl: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Normal longitudinal function", title: "Normal longitudinal function.", default: true },
                    { label: "Impaired longitudinal function", title: "Impaired longitudinal function." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOrder: 14,
            },        
        },
    },
    {
        title: "Right Atrium",
        params: {
            RAtrium: {
                title: "",
                custom: true, 
                conditionalText: true,
                options: [
                    { label: "Normal size", title: "Normal size.", default: true },
                    { label: "Dilated", title: "Dilated." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
            },
        },
    },
    {
        title: "Tricuspid Valve",
        params: {
            TV: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Normal leaflets", title: "Thin and mobile leaflets, opens well.", default: true },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
            },
            TS: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No stenosis", title: "No tricuspid stenosis.", default: true },
                    { label: "Mild stenosis", title: "Mild tricuspid stenosis." },
                    { label: "Moderate stenosis", title: "Moderate tricuspid stenosis." },
                    { label: "Severe stenosis", title: "Severe tricuspid stenosis." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOnChange: true,
                summaryOrder: 35,
            },
            TR: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Trivial regurgitation", title: "Trivial tricuspid regurgitation.", default: true },
                    { label: "Mild regurgitation", title: "Mild tricuspid regurgitation." },
                    { label: "Moderate regurgitation", title: "Moderate tricuspid regurgitation." },
                    { label: "Severe regurgitation", title: "Severe tricuspid regurgitation." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOrder: 36,
            },
        },
    },
    {
        title: "Pulmonary Valve",
        params: {
            PV: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Normal leaflets", title: "Thin and mobile cusps where seen.", default: true },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
            },
            PS: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No stenosis", title: "Normal forward flow and CW Doppler profile.", default: true },
                    { label: "Mild stenosis", title: "Mild pulmonary stenosis." },
                    { label: "Moderate stenosis", title: "Moderate pulmonary stenosis." },
                    { label: "Severe stenosis", title: "Severe pulmonary stenosis." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOnChange: true,
                summaryOrder: 37,
            },
            PR: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Trivial regurgitation", title: "Trivial pulmonary regurgitation.", default: true },
                    { label: "Mild regurgitation", title: "Mild pulmonary regurgitation." },
                    { label: "Moderate regurgitation", title: "Moderate pulmonary regurgitation." },
                    { label: "Severe regurgitation", title: "Severe pulmonary regurgitation." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
                summaryOnChange: true,
                summaryOrder: 38,
            },
            PVN: {
                title: "",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No systolic notch", title: "No mid-systolic notch.", default: true },
                    { label: "Systolic notch demonstrated", title: "Systolic notch demonstrated." },
                ],
            },
        },
    },
        
    {
        title: "Miscellaneous",
        params: {
            IVCD: {
                title: "IVC Size",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Not dilated", title: "not dilated", default: true },
                    { label: "Dilated", title: "dilated" },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
            },
            IVCC: {
                title: "IVC Collapse",
                options: [
                    { label: "Normal", title: "> 50%", default: true },
                    { label: "No collapse", title: "< 50%" },
                ],
            },
            RAP: {
                title: "RA Pressure",
                options: [
                    { label: "0-5mmHg", title: "0-5", default: true },
                    { label: "5-15mmHg", title: "5-15" },
                    { label: ">15mmHg", title: ">15" },
                ],
            },
            PPHT: {
                title: "Probability of PHT",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "Low", title: "Low echocardiographic probability of pulmonary hypertension", default: true },
                    { label: "Intermediate", title: "Intermediate echocardiographic probability of pulmonary hypertension" },
                    { label: "High", title: "High echocardiographic probability of pulmonary hypertension" },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
            },
            PASP: {
                title: "PASP =",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "not estimated in the absence of TR Vmax.", title: "not estimated in the absence of TR Vmax.", default: true },
                    { label: "(enter free text --&gt;)", title: "" },
                ]
            },
            ASD: {
                title: "Atrial Septal Defect",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No obvious ASD", title: "No obvious atrial septal defect imaged on CFM.", default: true },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
            },
            PEff: {
                title: "Pericardial Effusion",
                custom: true,
                conditionalText: true,
                options: [
                    { label: "No pericardial effusion", title: "No pericardial effusion.", default: true },
                    { label: "Trivial pericardial effusion", title: "Trivial pericardial effusion." },
                    { label: "(enter free text --&gt;)", title: "" },
                ],
                enableSummary: true,
                summaryDefault: false,
            },
        },
    },
    {
        title: "Summary",
        params: {
            SummaryLV: {
                title: "",
                options: [
                    { label: "Normal LV", title: "Normal left ventricular systolic function.\n - Normal LV internal cavity dimensions.\n - Normal LV wall thickness.", default: true },
                ],
                enableSummary: true,
                summaryDefault: true,
                summaryOrder: 10,
            },
            SummaryRV: {
                title: "",
                options: [
                    { label: "Normal RV", title: "Normal right ventricular size and function.", default: true },
                ],
                enableSummary: true,
                summaryDefault: true,
                summaryOrder: 20,
            },
            SummaryValves: {
                title: "",
                options: [
                    { label: "Normal valves", title: "No significant valvular abnormalities.", default: true },
                ],
                enableSummary: true,
                summaryDefault: true,
                summaryOrder: 30,
            },
            Summary: {
                title: "",
                custom: true,
                large: true,
            },
        },
    },
];